title: Matthew Garcia Portfolio
logo: docs/assets/Headshot_Circle.png
description: Senior Computer Engineering student with a focus on robotics, embedded systems, and IT. This portfolio showcases my academic and personal engineering projects.
theme: jekyll-theme-minimal

